create table chat_record
(
    id              bigint generated by default as identity
        constraint chat_record_pkey
            primary key,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null,
    user_id         varchar,
    input_text       varchar,
    output_text      text,
    is_public       boolean default true,
    language        varchar,
    uid             varchar,
    title           varchar
);

comment on table chat_record is 'chat_record table';

comment on column chat_record.id is 'sequence id';

comment on column chat_record.created_at is 'create time';

comment on column chat_record.updated_at is 'update time';

comment on column chat_record.user_id is 'user uuid';

comment on column chat_record.input_text is 'user input text';

comment on column chat_record.output_text is 'output_text';

comment on column chat_record.is_public is 'is_public';

comment on column chat_record.language is 'language';

comment on column chat_record.uid is 'uid';

comment on column chat_record.title is 'title';

